### ISSUE TITLE
Installation on localhost in xampp

### ISSUE THREAD

**Issue by energiatel** [UserApplePie/UserApplePie-v3#35]
I've installed UserApplePie-v3 on localhost with xampp (windows).
So folder is C:\xampp\htdocs\projectname\

I've moved UserApplePie public folder content to C:\xampp\htdocs\projectname\ (and imported sql and used composer)

When visiting http://localhost/projectname/ i can see welcome page.

In Config.php i have:
define('SITEURL', 'http://localhost/projectname/');
define('DIR', '/projectname/');

But when on welcome page i click on login (or register) the link is http://localhost/projectname/Login and  i get error "Object not found! The requested URL was not found on this server. [...]"

What am i doing wrong?

Many thanks

P.S. I couldn't register on official website because i got an error: "An error occurred, The error has been reported." on "http://userapplepie.com/Register" after clicking on "register"

**Comment by davarravad** [comment]
Thank you for the heads up on http://www.userapplepie.com

I was able to track that error down to a database setting.  Should be working now.

**Comment by davarravad** [comment]
As for your issue with removing the public folder.

I have not yet tried to install UAP3 this way.  However I think you need to change the following in index.php:

```
/** Define the absolute paths for configured directories */
define('APPDIR', realpath(__DIR__.'/../app/').'/');
define('SYSTEMDIR', realpath(__DIR__.'/../system/').'/');
define('PUBLICDIR', realpath(__DIR__).'/');
define('ROOTDIR', realpath(__DIR__.'/../').'/');
```
To
```
/** Define the absolute paths for configured directories */
define('APPDIR', realpath(__DIR__.'./app/').'/');
define('SYSTEMDIR', realpath(__DIR__.'./system/').'/');
define('PUBLICDIR', realpath(__DIR__).'/');
define('ROOTDIR', realpath(__DIR__.'./').'/');
```
Let me know if that works.  If not I will do further testing.

**Comment by davarravad** [comment]
I tested on my server and was able to get it working by editing the .htaccess file as well.

Change the following:
```
RewriteBase /
```
to
```
RewriteBase /projectname/
```

**Comment by energiatel** [comment]
Now it works! Thanks a lot!
